!function (e) {
  const t = e.th = e.th || {};
  t.dictionary = Object.assign(t.dictionary || {}, {
    "%0 of %1": "",
    "Block quote": "คำพูด",
    Cancel: "ยกเลิก",
    "Cannot upload file:": "ไม่สามารถอัปโหลดไฟล์ได้:",
    "Centered image": "จัดแนวรูปกึ่งกลาง",
    "Change image text alternative": "เปลี่ยนข้อความเมื่อไม่พบรูป",
    "Choose heading": "เลือกขนาดหัวข้อ",
    Column: "คอลัมน์",
    "Decrease indent": "ลดการเยื้อง",
    "Delete column": "ลบคอลัมน์",
    "Delete row": "ลบแถว",
    "Dropdown toolbar": "",
    "Editor toolbar": "",
    "Enter image caption": "คลิกเพื่อใส่คำอธิบายภาพ",
    "Full size image": "รูปขนาดเต็ม",
    "Header column": "หัวข้อคอลัมน์",
    "Header row": "ส่วนหัวแถว",
    Heading: "หัวข้อ",
    "Heading 1": "หัวข้อระดับ 1",
    "Heading 2": "หัวข้อระดับ 2",
    "Heading 3": "หัวข้อระดับ 3",
    "Heading 4": "หัวข้อระดับ 4",
    "Heading 5": "หัวข้อระดับ 5",
    "Heading 6": "หัวข้อระดับ 6",
    "Image toolbar": "เครื่องมือรูปภาพ",
    "image widget": "วิดเจ็ตรูปภาพ",
    "Increase indent": "เพิ่มการเยื้อง",
    "Insert column left": "แทรกคอลัมน์ทางซ้าย",
    "Insert column right": "แทรกคอลัมน์ทางขวา",
    "Insert image": "แทรกรูป",
    "Insert paragraph after block": "เพิ่มย่อหน้าหลังบล็อคนี้",
    "Insert paragraph before block": "เพิ่มย่อหน้าก่อนบล็อคนี้",
    "Insert row above": "แทรกส่วนหัวด้านบน",
    "Insert row below": "แทรกส่วนหัวด้านล่าง",
    "Insert table": "แทรกตาราง",
    "Left aligned image": "จัดแนวภาพซ้าย",
    "Merge cell down": "ผสานเซลล์ด้านล่าง",
    "Merge cell left": "ผสานเซลล์ด้านซ้าย",
    "Merge cell right": "ผสานเซลล์ด้านขวา",
    "Merge cell up": "ผสานเซลล์ด้านบน",
    "Merge cells": "ผสานเซลล์",
    Next: "ถัดไป",
    Paragraph: "ย่อหน้า",
    Previous: "ก่อนหน้า",
    Redo: "ทำซ้ำ",
    "Rich Text Editor": "",
    "Rich Text Editor, %0": "",
    "Right aligned image": "จัดแนวภาพขวา",
    Row: "แถว",
    Save: "บันทึก",
    "Select column": "",
    "Select row": "",
    "Show more items": "",
    "Side image": "รูปด้านข้าง",
    "Split cell horizontally": "แยกเซลล์แนวนอน",
    "Split cell vertically": "แยกเซลล์แนวตั้ง",
    "Table toolbar": "เครื่องมือตาราง",
    "Text alternative": "ข้อความเมื่อไม่พบรูป",
    Undo: "ย้อนกลับ",
    "Upload failed": "อัปโหลดไม่สำเร็จ",
    "Upload in progress": "กำลังดำเนินการอัปโหลด",
    "Widget toolbar": "แถบเครื่องมือวิดเจ็ต"
  }), t.getPluralForm = function (e) {
    return 0
  }
}(window.CKEDITOR_TRANSLATIONS || (window.CKEDITOR_TRANSLATIONS = {}));
